import type { PlantationArea } from '@/lib/types'

// Coordinates (mapX/mapY/mapWidth/mapHeight, percentages) mirror the real
// estate layout: facilities + big Gurmar block on the left, access road down
// the middle, crop columns on the right, Moringa/Banana/Passion along the
// bottom-right. See components/map/MapClient.tsx for the paired facilities.
export const areas: PlantationArea[] = [
  {
    id: 'area-hibiscus-1',
    name: 'Hibiscus - Roadside Plot',
    sizeAcres: 0.6,
    cropId: 'crop-hibiscus',
    variety: 'Hibiscus rosa-sinensis',
    plantCount: 220,
    plantingDate: '2023-04-12',
    expectedHarvestDate: '2026-07-20',
    growthStage: 'Flowering',
    healthStatus: 'healthy',
    aiHealthScore: 90,
    lastInspection: '2026-07-05',
    assignedStaff: ['R Thambiraja'],
    irrigationMethod: 'Manual watering',
    fertilizerSchedule: 'Organic compost every 4 weeks',
    diseaseStatus: 'None detected',
    pestStatus: 'Low',
    mapX: 52, mapY: 0, mapWidth: 23, mapHeight: 15,
  },
  {
    id: 'area-gurmar-1',
    name: 'Gurmar - North Plot',
    sizeAcres: 1.1,
    cropId: 'crop-gurmar',
    variety: 'Gymnema sylvestre',
    plantCount: 1800,
    plantingDate: '2022-08-01',
    expectedHarvestDate: '2026-07-15',
    growthStage: 'Leaf maturity',
    healthStatus: 'attention',
    aiHealthScore: 76,
    lastInspection: '2026-07-04',
    assignedStaff: ['W A A N Wijesooriya'],
    irrigationMethod: 'Rain-fed',
    fertilizerSchedule: 'Compost + organic manure every 6 weeks',
    diseaseStatus: 'Mild leaf spotting observed',
    pestStatus: 'Low',
    mapX: 52, mapY: 15, mapWidth: 23, mapHeight: 15,
  },
  {
    id: 'area-papaya',
    name: 'Papaya Plot',
    sizeAcres: 0.5,
    cropId: 'crop-papaya',
    variety: 'Red Lady',
    plantCount: 180,
    plantingDate: '2023-11-01',
    expectedHarvestDate: '2026-07-28',
    growthStage: 'Fruiting',
    healthStatus: 'moderate',
    aiHealthScore: 58,
    lastInspection: '2026-07-06',
    assignedStaff: ['W A A N Wijesooriya'],
    irrigationMethod: 'Drip irrigation',
    fertilizerSchedule: 'NPK 12:12:17 every 5 weeks',
    diseaseStatus: 'Powdery mildew on lower leaves',
    pestStatus: 'Fruit fly presence',
    mapX: 52, mapY: 30, mapWidth: 23, mapHeight: 8,
  },
  {
    id: 'area-mango',
    name: 'Mango Grove',
    sizeAcres: 1.3,
    cropId: 'crop-mango',
    variety: 'Karutha Colomban',
    plantCount: 16,
    plantingDate: '2020-05-15',
    expectedHarvestDate: '2026-08-05',
    growthStage: 'Fruit development',
    healthStatus: 'healthy',
    aiHealthScore: 95,
    lastInspection: '2026-07-03',
    assignedStaff: ['W.G. Dissanayaka'],
    irrigationMethod: 'Drip irrigation',
    fertilizerSchedule: 'Organic manure every 8 weeks',
    diseaseStatus: 'None detected',
    pestStatus: 'None',
    mapX: 52, mapY: 38, mapWidth: 23, mapHeight: 8,
  },
  {
    id: 'area-hibiscus-2',
    name: 'Hibiscus - Main Plot',
    sizeAcres: 1.4,
    cropId: 'crop-hibiscus',
    variety: 'Hibiscus rosa-sinensis',
    plantCount: 420,
    plantingDate: '2023-04-12',
    expectedHarvestDate: '2026-07-20',
    growthStage: 'Flowering',
    healthStatus: 'healthy',
    aiHealthScore: 88,
    lastInspection: '2026-07-05',
    assignedStaff: ['N M G Dharmasena'],
    irrigationMethod: 'Manual watering',
    fertilizerSchedule: 'Organic compost every 4 weeks',
    diseaseStatus: 'None detected',
    pestStatus: 'Low',
    mapX: 77, mapY: 0, mapWidth: 23, mapHeight: 18,
  },
  {
    id: 'area-coffee',
    name: 'Crop-Free Plot (Former Coffee)',
    sizeAcres: 0.9,
    cropId: '',
    variety: 'None - crop-free, pending new planting',
    plantCount: 0,
    plantingDate: '2021-09-01',
    expectedHarvestDate: '2026-11-01',
    growthStage: 'Coffee removed - crop-free, awaiting new planting decision',
    healthStatus: 'healthy',
    aiHealthScore: 0,
    lastInspection: '2026-07-02',
    assignedStaff: ['N M G Dharmasena'],
    irrigationMethod: 'N/A - no crop planted',
    fertilizerSchedule: 'N/A - no crop planted',
    diseaseStatus: 'N/A',
    pestStatus: 'N/A',
    mapX: 77, mapY: 18, mapWidth: 23, mapHeight: 7,
  },
  {
    id: 'area-moringa',
    name: 'Moringa Plot',
    sizeAcres: 1.0,
    cropId: 'crop-moringa',
    variety: 'Moringa oleifera (PKM-1)',
    plantCount: 60,
    plantingDate: '2022-06-20',
    expectedHarvestDate: '2026-07-22',
    growthStage: 'Leaf harvest ready',
    healthStatus: 'healthy',
    aiHealthScore: 91,
    lastInspection: '2026-07-06',
    assignedStaff: ['W.G. Dissanayaka'],
    irrigationMethod: 'Rain-fed',
    fertilizerSchedule: 'Compost every 8 weeks',
    diseaseStatus: 'None detected',
    pestStatus: 'None',
    mapX: 52, mapY: 50, mapWidth: 12, mapHeight: 50,
  },
  {
    id: 'area-banana',
    name: 'Banana Plot',
    sizeAcres: 1.2,
    cropId: 'crop-banana',
    variety: 'Kolikuttu',
    plantCount: 180,
    plantingDate: '2023-01-10',
    expectedHarvestDate: '2026-08-01',
    growthStage: 'Bunching',
    healthStatus: 'attention',
    aiHealthScore: 73,
    lastInspection: '2026-07-05',
    assignedStaff: ['W.G. Dissanayaka'],
    irrigationMethod: 'Drip irrigation',
    fertilizerSchedule: 'NPK 14:14:14 every 6 weeks',
    diseaseStatus: 'Early Sigatoka leaf spot',
    pestStatus: 'Low',
    mapX: 64, mapY: 50, mapWidth: 12, mapHeight: 50,
  },
  {
    id: 'area-passion',
    name: 'Passion Fruit Plot',
    sizeAcres: 1.6,
    cropId: 'crop-passion',
    variety: 'Purple Passion',
    plantCount: 225,
    plantingDate: '2023-02-05',
    expectedHarvestDate: '2026-07-16',
    growthStage: 'Fruiting - stressed',
    healthStatus: 'critical',
    aiHealthScore: 42,
    lastInspection: '2026-07-06',
    assignedStaff: ['Malar Kanthi'],
    irrigationMethod: 'Daily drip irrigation',
    fertilizerSchedule: 'Overdue - NPK 15:15:15 every 4 weeks',
    diseaseStatus: 'Fusarium wilt spreading on vines',
    pestStatus: 'Moderate fruit fly infestation',
    mapX: 80, mapY: 50, mapWidth: 20, mapHeight: 50,
  },
  {
    id: 'area-gurmar-2',
    name: 'Gurmar - South Block',
    sizeAcres: 1.9,
    cropId: 'crop-gurmar',
    variety: 'Gymnema sylvestre',
    plantCount: 1900,
    plantingDate: '2022-08-01',
    expectedHarvestDate: '2026-07-15',
    growthStage: 'Leaf maturity',
    healthStatus: 'healthy',
    aiHealthScore: 93,
    lastInspection: '2026-07-06',
    assignedStaff: ['R Thambiraja', 'W A A N Wijesooriya'],
    irrigationMethod: 'Rain-fed',
    fertilizerSchedule: 'Compost + organic manure every 6 weeks',
    diseaseStatus: 'None detected',
    pestStatus: 'None',
    mapX: 0, mapY: 46, mapWidth: 20, mapHeight: 24,
  },
  {
    id: 'area-soursop-ginger',
    name: 'Soursop & Ginger Plot',
    sizeAcres: 0.6,
    cropId: 'crop-soursop-ginger',
    variety: 'Soursop intercropped with Ginger',
    plantCount: 18,
    plantingDate: '2022-03-01',
    expectedHarvestDate: '2026-09-10',
    growthStage: 'Vegetative growth',
    healthStatus: 'attention',
    aiHealthScore: 71,
    lastInspection: '2026-07-04',
    assignedStaff: ['R Thambiraja'],
    irrigationMethod: 'Manual watering',
    fertilizerSchedule: 'Compost every 6 weeks',
    diseaseStatus: 'Ginger rhizome rot risk - monitoring',
    pestStatus: 'Low',
    mapX: 20, mapY: 46, mapWidth: 8, mapHeight: 24,
  },
  {
    id: 'area-roses',
    name: 'Roses Plot',
    sizeAcres: 0.4,
    cropId: 'crop-roses',
    variety: 'Rosa damascena',
    plantCount: 320,
    plantingDate: '2023-06-10',
    expectedHarvestDate: '2026-07-12',
    growthStage: 'Flowering',
    healthStatus: 'healthy',
    aiHealthScore: 85,
    lastInspection: '2026-07-05',
    assignedStaff: ['W A A N Wijesooriya'],
    irrigationMethod: 'Drip irrigation',
    fertilizerSchedule: 'Bone meal every 4 weeks',
    diseaseStatus: 'None detected',
    pestStatus: 'Aphids - minor',
    mapX: 28, mapY: 46, mapWidth: 5, mapHeight: 24,
  },
  {
    id: 'area-turmeric',
    name: 'Turmeric Plot',
    sizeAcres: 0.5,
    cropId: 'crop-turmeric',
    variety: 'Local yellow',
    plantCount: 650,
    plantingDate: '2025-12-01',
    expectedHarvestDate: '2026-09-15',
    growthStage: 'Rhizome bulking',
    healthStatus: 'healthy',
    aiHealthScore: 87,
    lastInspection: '2026-07-05',
    assignedStaff: ['Malar Kanthi'],
    irrigationMethod: 'Manual watering',
    fertilizerSchedule: 'Organic compost every 6 weeks',
    diseaseStatus: 'None detected',
    pestStatus: 'None',
    mapX: 11, mapY: 70, mapWidth: 9, mapHeight: 15,
  },
]

export function getAreaById(id: string) {
  return areas.find((a) => a.id === id)
}
