import type { PlantationArea } from '@/lib/types'

// Coordinates (mapX/mapY/mapWidth/mapHeight, percentages) mirror the real
// estate layout: facilities + big Gurmar block on the left, access road down
// the middle, crop columns on the right, Moringa/Banana/Passion along the
// bottom-right. See components/map/MapClient.tsx for the paired facilities.
export const areas: PlantationArea[] = [
  {
    id: 'area-hibiscus-1',
    name: 'Hibiscus - Roadside Plot',
    sizeAcres: 0.6,
    gpsLocation: '7.2906° N, 80.6337° E',
    cropId: 'crop-hibiscus',
    variety: 'Hibiscus rosa-sinensis',
    plantCount: 220,
    plantingDate: '2023-04-12',
    expectedHarvestDate: '2026-07-20',
    growthStage: 'Flowering',
    healthStatus: 'healthy',
    aiHealthScore: 90,
    lastInspection: '2026-07-05',
    assignedStaff: ['R Thambiraja'],
    irrigationMethod: 'Manual watering',
    fertilizerSchedule: 'Organic compost every 4 weeks',
    diseaseStatus: 'None detected',
    pestStatus: 'Low',
    mapX: 52, mapY: 0, mapWidth: 23, mapHeight: 15,
  },
  {
    id: 'area-gurmar-1',
    name: 'Gurmar - North Plot',
    sizeAcres: 1.1,
    gpsLocation: '7.2909° N, 80.6340° E',
    cropId: 'crop-gurmar',
    variety: 'Gymnema sylvestre',
    plantCount: 640,
    plantingDate: '2022-08-01',
    expectedHarvestDate: '2026-07-15',
    growthStage: 'Leaf maturity',
    healthStatus: 'attention',
    aiHealthScore: 76,
    lastInspection: '2026-07-04',
    assignedStaff: ['W A A N Wijesooriya'],
    irrigationMethod: 'Rain-fed',
    fertilizerSchedule: 'Compost + organic manure every 6 weeks',
    diseaseStatus: 'Mild leaf spotting observed',
    pestStatus: 'Low',
    mapX: 52, mapY: 15, mapWidth: 23, mapHeight: 15,
  },
  {
    id: 'area-papaya',
    name: 'Papaya Plot',
    sizeAcres: 0.5,
    gpsLocation: '7.2911° N, 80.6342° E',
    cropId: 'crop-papaya',
    variety: 'Red Lady',
    plantCount: 180,
    plantingDate: '2023-11-01',
    expectedHarvestDate: '2026-07-28',
    growthStage: 'Fruiting',
    healthStatus: 'moderate',
    aiHealthScore: 58,
    lastInspection: '2026-07-06',
    assignedStaff: ['W A A N Wijesooriya'],
    irrigationMethod: 'Drip irrigation',
    fertilizerSchedule: 'NPK 12:12:17 every 5 weeks',
    diseaseStatus: 'Powdery mildew on lower leaves',
    pestStatus: 'Fruit fly presence',
    mapX: 52, mapY: 30, mapWidth: 23, mapHeight: 8,
  },
  {
    id: 'area-mango',
    name: 'Mango Grove',
    sizeAcres: 1.3,
    gpsLocation: '7.2913° N, 80.6344° E',
    cropId: 'crop-mango',
    variety: 'Karutha Colomban',
    plantCount: 45,
    plantingDate: '2020-05-15',
    expectedHarvestDate: '2026-08-05',
    growthStage: 'Fruit development',
    healthStatus: 'healthy',
    aiHealthScore: 95,
    lastInspection: '2026-07-03',
    assignedStaff: ['W.G. Dissanayaka'],
    irrigationMethod: 'Drip irrigation',
    fertilizerSchedule: 'Organic manure every 8 weeks',
    diseaseStatus: 'None detected',
    pestStatus: 'None',
    mapX: 52, mapY: 38, mapWidth: 23, mapHeight: 8,
  },
  {
    id: 'area-hibiscus-2',
    name: 'Hibiscus - Main Plot',
    sizeAcres: 1.4,
    gpsLocation: '7.2915° N, 80.6360° E',
    cropId: 'crop-hibiscus',
    variety: 'Hibiscus rosa-sinensis',
    plantCount: 420,
    plantingDate: '2023-04-12',
    expectedHarvestDate: '2026-07-20',
    growthStage: 'Flowering',
    healthStatus: 'healthy',
    aiHealthScore: 88,
    lastInspection: '2026-07-05',
    assignedStaff: ['N M G Dharmasena'],
    irrigationMethod: 'Manual watering',
    fertilizerSchedule: 'Organic compost every 4 weeks',
    diseaseStatus: 'None detected',
    pestStatus: 'Low',
    mapX: 77, mapY: 0, mapWidth: 23, mapHeight: 18,
  },
  {
    id: 'area-coffee',
    name: 'Coffee Plot',
    sizeAcres: 0.9,
    gpsLocation: '7.2917° N, 80.6362° E',
    cropId: 'crop-coffee',
    variety: 'Coffea arabica',
    plantCount: 260,
    plantingDate: '2021-09-01',
    expectedHarvestDate: '2026-11-01',
    growthStage: 'Berry development',
    healthStatus: 'moderate',
    aiHealthScore: 64,
    lastInspection: '2026-07-02',
    assignedStaff: ['N M G Dharmasena'],
    irrigationMethod: 'Shade grown, rain-fed',
    fertilizerSchedule: 'NPK 17:17:17 every 8 weeks',
    diseaseStatus: 'Leaf rust - early stage',
    pestStatus: 'Berry borer detected',
    mapX: 77, mapY: 18, mapWidth: 23, mapHeight: 7,
  },
  {
    id: 'area-pomegranate',
    name: 'Pomegranate Plot',
    sizeAcres: 0.7,
    gpsLocation: '7.2919° N, 80.6364° E',
    cropId: 'crop-pomegranate',
    variety: 'Bhagwa',
    plantCount: 140,
    plantingDate: '2022-02-14',
    expectedHarvestDate: '2026-08-20',
    growthStage: 'Fruit set',
    healthStatus: 'healthy',
    aiHealthScore: 89,
    lastInspection: '2026-07-04',
    assignedStaff: ['N M G Dharmasena'],
    irrigationMethod: 'Drip irrigation',
    fertilizerSchedule: 'Organic manure every 8 weeks',
    diseaseStatus: 'None detected',
    pestStatus: 'Low',
    mapX: 77, mapY: 25, mapWidth: 23, mapHeight: 7,
  },
  {
    id: 'area-moringa',
    name: 'Moringa Plot',
    sizeAcres: 1.0,
    gpsLocation: '7.2895° N, 80.6355° E',
    cropId: 'crop-moringa',
    variety: 'Moringa oleifera (PKM-1)',
    plantCount: 750,
    plantingDate: '2022-06-20',
    expectedHarvestDate: '2026-07-22',
    growthStage: 'Leaf harvest ready',
    healthStatus: 'healthy',
    aiHealthScore: 91,
    lastInspection: '2026-07-06',
    assignedStaff: ['W.G. Dissanayaka'],
    irrigationMethod: 'Rain-fed',
    fertilizerSchedule: 'Compost every 8 weeks',
    diseaseStatus: 'None detected',
    pestStatus: 'None',
    mapX: 52, mapY: 50, mapWidth: 12, mapHeight: 50,
  },
  {
    id: 'area-banana',
    name: 'Banana Plot',
    sizeAcres: 1.2,
    gpsLocation: '7.2893° N, 80.6357° E',
    cropId: 'crop-banana',
    variety: 'Kolikuttu',
    plantCount: 380,
    plantingDate: '2023-01-10',
    expectedHarvestDate: '2026-08-01',
    growthStage: 'Bunching',
    healthStatus: 'attention',
    aiHealthScore: 73,
    lastInspection: '2026-07-05',
    assignedStaff: ['W.G. Dissanayaka'],
    irrigationMethod: 'Drip irrigation',
    fertilizerSchedule: 'NPK 14:14:14 every 6 weeks',
    diseaseStatus: 'Early Sigatoka leaf spot',
    pestStatus: 'Low',
    mapX: 64, mapY: 50, mapWidth: 12, mapHeight: 50,
  },
  {
    id: 'area-passion',
    name: 'Passion Fruit Plot',
    sizeAcres: 1.6,
    gpsLocation: '7.2890° N, 80.6362° E',
    cropId: 'crop-passion',
    variety: 'Purple Passion',
    plantCount: 480,
    plantingDate: '2023-02-05',
    expectedHarvestDate: '2026-07-16',
    growthStage: 'Fruiting - stressed',
    healthStatus: 'critical',
    aiHealthScore: 42,
    lastInspection: '2026-07-06',
    assignedStaff: ['Malar Kanthi'],
    irrigationMethod: 'Daily drip irrigation',
    fertilizerSchedule: 'Overdue - NPK 15:15:15 every 4 weeks',
    diseaseStatus: 'Fusarium wilt spreading on vines',
    pestStatus: 'Moderate fruit fly infestation',
    mapX: 80, mapY: 50, mapWidth: 20, mapHeight: 50,
  },
  {
    id: 'area-gurmar-2',
    name: 'Gurmar - South Block',
    sizeAcres: 1.9,
    gpsLocation: '7.2880° N, 80.6320° E',
    cropId: 'crop-gurmar',
    variety: 'Gymnema sylvestre',
    plantCount: 1210,
    plantingDate: '2022-08-01',
    expectedHarvestDate: '2026-07-15',
    growthStage: 'Leaf maturity',
    healthStatus: 'healthy',
    aiHealthScore: 93,
    lastInspection: '2026-07-06',
    assignedStaff: ['R Thambiraja', 'W A A N Wijesooriya'],
    irrigationMethod: 'Rain-fed',
    fertilizerSchedule: 'Compost + organic manure every 6 weeks',
    diseaseStatus: 'None detected',
    pestStatus: 'None',
    mapX: 0, mapY: 46, mapWidth: 20, mapHeight: 24,
  },
  {
    id: 'area-soursop-ginger',
    name: 'Soursop & Ginger Plot',
    sizeAcres: 0.6,
    gpsLocation: '7.2878° N, 80.6325° E',
    cropId: 'crop-soursop-ginger',
    variety: 'Soursop intercropped with Ginger',
    plantCount: 210,
    plantingDate: '2022-03-01',
    expectedHarvestDate: '2026-09-10',
    growthStage: 'Vegetative growth',
    healthStatus: 'attention',
    aiHealthScore: 71,
    lastInspection: '2026-07-04',
    assignedStaff: ['R Thambiraja'],
    irrigationMethod: 'Manual watering',
    fertilizerSchedule: 'Compost every 6 weeks',
    diseaseStatus: 'Ginger rhizome rot risk - monitoring',
    pestStatus: 'Low',
    mapX: 20, mapY: 46, mapWidth: 8, mapHeight: 24,
  },
  {
    id: 'area-roses',
    name: 'Roses Plot',
    sizeAcres: 0.4,
    gpsLocation: '7.2876° N, 80.6328° E',
    cropId: 'crop-roses',
    variety: 'Rosa damascena',
    plantCount: 320,
    plantingDate: '2023-06-10',
    expectedHarvestDate: '2026-07-12',
    growthStage: 'Flowering',
    healthStatus: 'healthy',
    aiHealthScore: 85,
    lastInspection: '2026-07-05',
    assignedStaff: ['W A A N Wijesooriya'],
    irrigationMethod: 'Drip irrigation',
    fertilizerSchedule: 'Bone meal every 4 weeks',
    diseaseStatus: 'None detected',
    pestStatus: 'Aphids - minor',
    mapX: 28, mapY: 46, mapWidth: 5, mapHeight: 24,
  },
  {
    id: 'area-mushroom',
    name: 'Mushroom House',
    sizeAcres: 0.2,
    gpsLocation: '7.2872° N, 80.6318° E',
    cropId: 'crop-mushroom',
    variety: 'Oyster Mushroom',
    plantCount: 400,
    plantingDate: '2026-06-01',
    expectedHarvestDate: '2026-07-10',
    growthStage: 'Fruiting bodies forming',
    healthStatus: 'moderate',
    aiHealthScore: 60,
    lastInspection: '2026-07-06',
    assignedStaff: ['Malar Kanthi'],
    irrigationMethod: 'Humidity misting',
    fertilizerSchedule: 'N/A - substrate based',
    diseaseStatus: 'Green mold contamination on 2 bags',
    pestStatus: 'None',
    mapX: 0, mapY: 70, mapWidth: 11, mapHeight: 15,
  },
  {
    id: 'area-turmeric',
    name: 'Turmeric Plot',
    sizeAcres: 0.5,
    gpsLocation: '7.2870° N, 80.6316° E',
    cropId: 'crop-turmeric',
    variety: 'Local yellow',
    plantCount: 2400,
    plantingDate: '2025-12-01',
    expectedHarvestDate: '2026-09-15',
    growthStage: 'Rhizome bulking',
    healthStatus: 'healthy',
    aiHealthScore: 87,
    lastInspection: '2026-07-05',
    assignedStaff: ['Malar Kanthi'],
    irrigationMethod: 'Manual watering',
    fertilizerSchedule: 'Organic compost every 6 weeks',
    diseaseStatus: 'None detected',
    pestStatus: 'None',
    mapX: 11, mapY: 70, mapWidth: 9, mapHeight: 15,
  },
]

export function getAreaById(id: string) {
  return areas.find((a) => a.id === id)
}
