import type { Crop } from '@/lib/types'

export const crops: Crop[] = [
  {
    id: 'crop-hibiscus',
    name: 'Hibiscus',
    variety: 'Hibiscus rosa-sinensis',
    plantCount: 640,
    plantingDate: '2022-01-01',
    expectedHarvestDate: '2026-07-20',
    harvestCycleDays: 21,
    growthStage: 'Flowering',
    waterRequirement: 'Medium - manual watering',
    fertilizerSchedule: 'Organic compost every 4 weeks',
    pesticideSchedule: 'Neem oil as needed',
    expectedYieldKg: 280,
    actualYieldKg: 13,
    costOfCultivation: 0,
    revenue: 56893,
  },
  {
    id: 'crop-gurmar',
    name: 'Gurmar',
    variety: 'Gymnema sylvestre',
    plantCount: 3700,
    plantingDate: '2022-01-01',
    expectedHarvestDate: '2026-07-15',
    harvestCycleDays: 90,
    growthStage: 'Leaf maturity',
    waterRequirement: 'Low - drought tolerant vine',
    fertilizerSchedule: 'Compost + organic manure every 6 weeks',
    pesticideSchedule: 'Neem oil monthly',
    expectedYieldKg: 920,
    actualYieldKg: 9,
    costOfCultivation: 0,
    revenue: 47959.30,
  },
  {
    id: 'crop-papaya',
    name: 'Papaya',
    variety: 'Red Lady',
    plantCount: 180,
    plantingDate: '2024-10-16',
    expectedHarvestDate: '2025-08-20',
    harvestCycleDays: 14,
    growthStage: 'Fruiting',
    waterRequirement: 'High - daily watering',
    fertilizerSchedule: 'NPK 12:12:17 every 5 weeks',
    pesticideSchedule: 'Fungicide preventive spray',
    expectedYieldKg: 1400,
    actualYieldKg: 173,
    costOfCultivation: 0,
    revenue: 16623,
  },
  {
    id: 'crop-mango',
    name: 'Mango',
    variety: 'Karutha Colomban',
    plantCount: 16,
    plantingDate: '2025-05-20',
    expectedHarvestDate: '2032-10-20',
    harvestCycleDays: 365,
    growthStage: 'Establishment (young tree - first fruiting not expected until ~2032)',
    waterRequirement: 'Medium - drip irrigation',
    fertilizerSchedule: 'Organic manure every 8 weeks',
    pesticideSchedule: 'Fruit fly trap + neem oil',
    expectedYieldKg: 2100,
    actualYieldKg: 0,
    costOfCultivation: 0,
    revenue: 0,
  },
  {
    id: 'crop-soursop-ginger',
    name: 'Soursop & Ginger',
    variety: 'Soursop (Annona muricata) intercropped with Ginger',
    plantCount: 18,
    plantingDate: '2022-03-01',
    expectedHarvestDate: '2026-09-10',
    harvestCycleDays: 180,
    growthStage: 'Vegetative growth',
    waterRequirement: 'Medium - manual watering',
    fertilizerSchedule: 'Compost every 6 weeks',
    pesticideSchedule: 'Neem oil as needed',
    expectedYieldKg: 640,
    actualYieldKg: 0,
    costOfCultivation: 0,
    revenue: 0,
  },
  {
    id: 'crop-roses',
    name: 'Roses',
    variety: 'Rosa damascena',
    plantCount: 320,
    plantingDate: '2023-06-10',
    expectedHarvestDate: '2026-07-12',
    harvestCycleDays: 10,
    growthStage: 'Flowering',
    waterRequirement: 'Medium - drip irrigation',
    fertilizerSchedule: 'Bone meal every 4 weeks',
    pesticideSchedule: 'Aphid control spray weekly',
    expectedYieldKg: 95,
    actualYieldKg: 0,
    costOfCultivation: 0,
    revenue: 0,
  },
  {
    id: 'crop-coffee',
    name: 'Coffee',
    variety: 'Coffea arabica',
    plantCount: 0,
    plantingDate: '2021-09-01',
    expectedHarvestDate: '2026-11-01',
    harvestCycleDays: 365,
    growthStage: 'Removed - plot now crop-free, pending new planting decision',
    waterRequirement: 'Medium - shade grown',
    fertilizerSchedule: 'NPK 17:17:17 every 8 weeks',
    pesticideSchedule: 'Berry borer monitoring',
    expectedYieldKg: 310,
    actualYieldKg: 0,
    costOfCultivation: 0,
    revenue: 0,
  },
  {
    id: 'crop-pomegranate',
    name: 'Pomegranate',
    variety: 'Bhagwa',
    plantCount: 0,
    plantingDate: '2025-11-20',
    expectedHarvestDate: '2026-08-20',
    harvestCycleDays: 180,
    growthStage: 'Not yet planted - land prepared only, plot removed from the map until planting begins',
    waterRequirement: 'Low - drought tolerant',
    fertilizerSchedule: 'Organic manure every 8 weeks',
    pesticideSchedule: 'Fruit borer trap',
    expectedYieldKg: 560,
    actualYieldKg: 0,
    costOfCultivation: 0,
    revenue: 0,
  },
  {
    id: 'crop-passion',
    name: 'Passion Fruit',
    variety: 'Purple Passion',
    plantCount: 225,
    plantingDate: '2024-02-13',
    expectedHarvestDate: '2025-10-08',
    harvestCycleDays: 14,
    growthStage: 'Fruiting - stressed',
    waterRequirement: 'High - daily irrigation',
    fertilizerSchedule: 'NPK 15:15:15 every 4 weeks',
    pesticideSchedule: 'Fungicide + insecticide rotation',
    expectedYieldKg: 1850,
    actualYieldKg: 33,
    costOfCultivation: 0,
    revenue: 12240,
  },
  {
    id: 'crop-moringa',
    name: 'Moringa',
    variety: 'Moringa oleifera (PKM-1)',
    plantCount: 60,
    plantingDate: '2024-02-02',
    expectedHarvestDate: '2025-10-08',
    harvestCycleDays: 45,
    growthStage: 'Leaf harvest ready',
    waterRequirement: 'Low - drought tolerant',
    fertilizerSchedule: 'Compost every 8 weeks',
    pesticideSchedule: 'Minimal - hardy crop',
    expectedYieldKg: 1050,
    actualYieldKg: 0,
    costOfCultivation: 0,
    revenue: 0,
  },
  {
    id: 'crop-banana',
    name: 'Banana',
    variety: 'Kolikuttu',
    plantCount: 180,
    plantingDate: '2025-11-20',
    expectedHarvestDate: '2026-09-20',
    harvestCycleDays: 300,
    growthStage: 'Bunching',
    waterRequirement: 'High - drip irrigation',
    fertilizerSchedule: 'NPK 14:14:14 every 6 weeks',
    pesticideSchedule: 'Sigatoka leaf spot monitoring',
    expectedYieldKg: 1600,
    actualYieldKg: 13,
    costOfCultivation: 0,
    revenue: 2540,
  },
  {
    id: 'crop-turmeric',
    name: 'Turmeric',
    variety: 'Local yellow',
    plantCount: 650,
    plantingDate: '2025-09-08',
    expectedHarvestDate: '2026-06-18',
    harvestCycleDays: 270,
    growthStage: 'Rhizome bulking',
    waterRequirement: 'Medium - manual watering',
    fertilizerSchedule: 'Organic compost every 6 weeks',
    pesticideSchedule: 'Rhizome rot monitoring',
    expectedYieldKg: 1900,
    actualYieldKg: 64,
    costOfCultivation: 0,
    revenue: 16125,
  },
  {
    id: 'crop-mushroom',
    name: 'Mushroom',
    variety: 'Oyster Mushroom',
    plantCount: 0,
    plantingDate: '2026-06-01',
    expectedHarvestDate: '2026-07-10',
    harvestCycleDays: 21,
    growthStage: 'Discontinued - Mushroom House converted to the Chicken Farm',
    waterRequirement: 'High humidity - misting',
    fertilizerSchedule: 'N/A - substrate based',
    pesticideSchedule: 'Contamination monitoring',
    expectedYieldKg: 260,
    actualYieldKg: 0,
    costOfCultivation: 0,
    revenue: 0,
  },
  {
    id: 'crop-hot-dragon',
    name: 'Hot Dragon',
    variety: 'Dragon Fruit (Pitaya)',
    plantCount: 0,
    plantingDate: '2025-08-18',
    expectedHarvestDate: '2025-12-15',
    harvestCycleDays: 240,
    growthStage: 'Multiple greenhouse cycles - see Greenhouse Tunnels below',
    waterRequirement: 'Drip irrigation, greenhouse grown',
    fertilizerSchedule: 'See per-tunnel expense breakdown below',
    pesticideSchedule: 'Not itemized in source data',
    expectedYieldKg: 3600,
    actualYieldKg: 3050,
    costOfCultivation: 1200375,
    revenue: 1170000,
  },
  {
    id: 'crop-muriya',
    name: 'Muriya',
    variety: 'Chili (Muriya)',
    plantCount: 0,
    plantingDate: '2025-07-19',
    expectedHarvestDate: '2025-09-16',
    harvestCycleDays: 60,
    growthStage: 'Multiple greenhouse cycles - see Greenhouse Tunnels below',
    waterRequirement: 'Drip irrigation, greenhouse grown',
    fertilizerSchedule: 'See per-tunnel expense breakdown below',
    pesticideSchedule: 'Not itemized in source data',
    expectedYieldKg: 1500,
    actualYieldKg: 1400,
    costOfCultivation: 880250,
    revenue: 440000,
  },
  {
    id: 'crop-cucumber',
    name: 'Cucumber',
    variety: 'Local cucumber',
    plantCount: 0,
    plantingDate: '2025-12-04',
    expectedHarvestDate: '2026-01-10',
    harvestCycleDays: 37,
    growthStage: 'Harvested - cleared 2026-02-20',
    waterRequirement: 'Not itemized in source data',
    fertilizerSchedule: 'Not itemized in source data',
    pesticideSchedule: 'Not itemized in source data',
    expectedYieldKg: 1000,
    actualYieldKg: 1000,
    costOfCultivation: 0,
    revenue: 60000,
  },
  {
    id: 'crop-kakiri',
    name: 'Kakiri',
    variety: 'Sri Lankan cucumber/melon',
    plantCount: 0,
    plantingDate: '2025-12-19',
    expectedHarvestDate: '2026-02-08',
    harvestCycleDays: 51,
    growthStage: 'Harvested - cleared 2026-03-31',
    waterRequirement: 'Not itemized in source data',
    fertilizerSchedule: 'Not itemized in source data',
    pesticideSchedule: 'Not itemized in source data',
    expectedYieldKg: 1000,
    actualYieldKg: 1000,
    costOfCultivation: 0,
    revenue: 50000,
  },
]

export function getCropById(id: string) {
  return crops.find((c) => c.id === id)
}
