import type { DailyUpdate } from '@/lib/types'

export const dailyUpdates: DailyUpdate[] = [
  {
    id: 'upd-1',
    date: '2026-07-06',
    areaId: 'area-passion',
    cropId: 'crop-passion',
    activity: 'Disease inspection',
    staff: ['Malar Kanthi'],
    weather: 'Overcast, light rain',
    wateringDetails: 'Skipped - sufficient rainfall',
    fertilizerApplied: 'None',
    pesticideApplied: 'None',
    diseasesFound: 'Fusarium wilt spreading on several vines',
    pestIssues: 'Moderate fruit fly infestation',
    notes: 'Flagged for urgent fungicide treatment and removal of wilting vines.',
    photoCount: 5,
  },
  {
    id: 'upd-2',
    date: '2026-07-06',
    areaId: 'area-turmeric',
    cropId: 'crop-turmeric',
    activity: 'Weeding',
    staff: ['Malar Kanthi'],
    weather: 'Sunny',
    wateringDetails: 'Manual, standard cycle',
    fertilizerApplied: 'None',
    pesticideApplied: 'None',
    diseasesFound: 'None',
    pestIssues: 'None',
    notes: 'Bed cleared, rhizomes bulking well.',
    photoCount: 3,
  },
  {
    id: 'upd-3',
    date: '2026-07-05',
    areaId: 'area-coffee',
    cropId: 'crop-coffee',
    activity: 'Pest control',
    staff: ['N M G Dharmasena'],
    weather: 'Humid',
    wateringDetails: 'Rain-fed',
    fertilizerApplied: 'None',
    pesticideApplied: 'Berry borer trap replacement',
    diseasesFound: 'Early leaf rust spotting',
    pestIssues: 'Berry borer detected',
    notes: 'Replaced pheromone traps, will re-inspect in 3 days.',
    photoCount: 4,
  },
  {
    id: 'upd-4',
    date: '2026-07-04',
    areaId: 'area-gurmar-1',
    cropId: 'crop-gurmar',
    activity: 'Fertilizing',
    staff: ['W A A N Wijesooriya'],
    weather: 'Clear',
    wateringDetails: 'Rain-fed',
    fertilizerApplied: 'Compost + organic manure, 15kg',
    pesticideApplied: 'None',
    diseasesFound: 'Mild leaf spotting',
    pestIssues: 'None',
    notes: 'Applied compost, monitoring leaf condition over next 2 weeks.',
    photoCount: 6,
  },
  {
    id: 'upd-5',
    date: '2026-07-03',
    areaId: 'area-gurmar-2',
    cropId: 'crop-gurmar',
    activity: 'Weeding',
    staff: ['R Thambiraja', 'W A A N Wijesooriya'],
    weather: 'Sunny',
    wateringDetails: 'Rain-fed',
    fertilizerApplied: 'None',
    pesticideApplied: 'None',
    diseasesFound: 'None',
    pestIssues: 'None',
    notes: 'Routine maintenance, block looking healthy ahead of leaf harvest.',
    photoCount: 2,
  },
  {
    id: 'upd-6',
    date: '2026-07-02',
    areaId: 'area-banana',
    cropId: 'crop-banana',
    activity: 'Disease inspection',
    staff: ['W.G. Dissanayaka'],
    weather: 'Dry spell',
    wateringDetails: 'Drip irrigation, standard cycle',
    fertilizerApplied: 'None',
    pesticideApplied: 'None',
    diseasesFound: 'Early Sigatoka leaf spot on lower leaves',
    pestIssues: 'None',
    notes: 'Marked affected leaves for removal next visit.',
    photoCount: 3,
  },
  {
    id: 'upd-7',
    date: '2026-07-01',
    areaId: 'area-mushroom',
    cropId: 'crop-mushroom',
    activity: 'Disease inspection',
    staff: ['Malar Kanthi'],
    weather: 'Humid',
    wateringDetails: 'Misting, 3x daily',
    fertilizerApplied: 'None',
    pesticideApplied: 'None',
    diseasesFound: 'Green mold contamination on 2 substrate bags',
    pestIssues: 'None',
    notes: 'Removed contaminated bags, improved ventilation.',
    photoCount: 4,
  },
]
