import type { PlantationTask } from '@/lib/types'

export const tasks: PlantationTask[] = [
  {
    id: 'task-1',
    title: 'Apply fungicide to Fusarium wilt',
    category: 'Spraying',
    assignedTo: 'Malar Kanthi',
    areaId: 'area-passion',
    dueDate: '2026-07-08',
    priority: 'urgent',
    status: 'in_progress',
    progress: 40,
    notes: 'Remove wilting vines first, then apply systemic fungicide.',
  },
  {
    id: 'task-2',
    title: 'Harvest ready passion fruit vines',
    category: 'Harvesting',
    assignedTo: 'Malar Kanthi',
    areaId: 'area-passion',
    dueDate: '2026-07-16',
    priority: 'high',
    status: 'pending',
    progress: 0,
  },
  {
    id: 'task-3',
    title: 'Gurmar leaf harvest - South Block',
    category: 'Harvesting',
    assignedTo: 'R Thambiraja',
    areaId: 'area-gurmar-2',
    dueDate: '2026-07-15',
    priority: 'medium',
    status: 'in_progress',
    progress: 65,
  },
  {
    id: 'task-4',
    title: 'Replace berry borer traps - Coffee',
    category: 'Spraying',
    assignedTo: 'N M G Dharmasena',
    areaId: 'area-coffee',
    dueDate: '2026-07-10',
    priority: 'high',
    status: 'pending',
    progress: 0,
  },
  {
    id: 'task-5',
    title: 'Remove Sigatoka-affected banana leaves',
    category: 'Maintenance',
    assignedTo: 'W.G. Dissanayaka',
    areaId: 'area-banana',
    dueDate: '2026-07-08',
    priority: 'medium',
    status: 'pending',
    progress: 0,
  },
  {
    id: 'task-6',
    title: 'Remove contaminated mushroom substrate bags',
    category: 'Cleaning',
    assignedTo: 'Malar Kanthi',
    areaId: 'area-mushroom',
    dueDate: '2026-07-09',
    priority: 'medium',
    status: 'in_progress',
    progress: 50,
  },
  {
    id: 'task-7',
    title: 'Weeding - Soursop & Ginger plot',
    category: 'Weeding',
    assignedTo: 'R Thambiraja',
    areaId: 'area-soursop-ginger',
    dueDate: '2026-07-01',
    priority: 'low',
    status: 'overdue',
    progress: 20,
  },
  {
    id: 'task-8',
    title: 'Equipment cleaning - sprayers',
    category: 'Cleaning',
    assignedTo: 'N M G Dharmasena',
    dueDate: '2026-06-30',
    priority: 'low',
    status: 'completed',
    progress: 100,
    notes: 'All sprayer nozzles cleaned and calibrated.',
  },
]
